package com.carhub.api.auto.domain.enumerations;

public enum SuspensionSystem {
    MCPHERSON_STRUT, DEPRECIATED_RACK, HELICAL_SPRING, ANTIROLL_SPRING, SPRING, COIL_SPRING, SUSPENSION_WITH_STEERING_ROD, MULTI_LINK_SPRING, MULTI_LINK_SPRING_WITH_ABSORBERS, MCPHERSON_SPRING_WITH_STABILIZER, SPRING_LOADED_RACK, HYDRAULIC, PNEUMATIC, HYDRO_PNEUMATIC, WISHBONE, DOUBLE_WISHBONE, INCLINED_LEVER, TRAPEZOIDAL_LEVER, BEAM_BRIDGE, ROTARY_FIST, TRANSVERSE_STABILIZER, TRAILING, TORSION, THREADED_TWIST_BEAM, ELASTIC_BEAM, DE_DION
}
