server.port=8083
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql = true
spring.datasource.url=jdbc:mysql://localhost:3306/db_lyne
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.username=lyne
spring.datasource.password=password-lyne
spring.security.user.name=user
spring.security.user.password=password


